Upgrade to python 3.8 (#31)
* Upgrade to python 3.8

* update poetry.lock file

* ignore mypy error:
 error: Type of decorated function contains type "Any" ("Callable[[DefaultNamedArg(Dict[Task, Dict[str, Type[Any]]], 'input'), DefaultNamedArg(Dict[Task, Dict[str, Type[Any]]], 'output')], None]")  [misc]